// TEXT MARKERS
var textMarkers = 
[{
    "name": "<span data-i18n='HIERACON'>HIERACON</span>",
    "coords": [5926,4846]
}, {
    "name": "<span data-i18n='SPEZIA'>SPEZIA</span>",
    "coords": [4090,4283]
}]
//Game Markers
var markers = 
[{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4449,5306],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4453,5319],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4457,5327],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4468,5322],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4480,5325],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4446,5326],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4444,5333],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4434,5327],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4429,5316],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4430,5311],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4431,5304],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4439,5296],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4482,5271],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4496,5247],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4533,5239],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4541,5245],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4547,5237],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4541,5235],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4544,5231],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4545,5225],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4542,5221],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4553,5213],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4558,5207],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4555,5198],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4546,5191],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4541,5190],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4527,5187],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4519,5194],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4515,5202],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4507,5226],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4526,5230],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4530,5236],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4519,5240],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4489,5253],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4484,5250],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4483,5258],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4496,5299],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4488,5313],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4489,5337],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4493,5348],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4414,5380],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4377,5389],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4368,5404],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4343,5402],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4336,5397],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4304,5404],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4311,5414],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4295,5367],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4302,5363],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4303,5336],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4308,5324],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4296,5321],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4291,5312],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4280,5302],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4284,5290],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4311,5309],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4312,5295],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4327,5293],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4336,5290],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4346,5277],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4356,5276],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4356,5289],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4356,5261],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4337,5262],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4337,5267],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4313,5259],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4308,5255],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4306,5243],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4297,5236],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4291,5251],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4284,5241],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4294,5231],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4277,5228],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4281,5216],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4315,5237],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4320,5252],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4322,5261],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4322,5229],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4321,5222],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4342,5222],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4334,5230],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4344,5260],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4355,5270],
}]
