// TEXT MARKERS
var textMarkers = 
[{
    "name": "<span data-i18n='HIERACON'>HIERACON</span>",
    "coords": [5926,4846]
}, {
    "name": "<span data-i18n='SPEZIA'>SPEZIA</span>",
    "coords": [4090,4283]
}]
//Game Markers
var markers = 
[
//IRON
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4449,5306],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4453,5319],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4457,5327],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4468,5322],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4480,5325],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4446,5326],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4444,5333],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4434,5327],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4429,5316],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4430,5311],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4431,5304],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4439,5296],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4482,5271],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4496,5247],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4533,5239],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4541,5245],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4547,5237],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4541,5235],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4544,5231],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4545,5225],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4542,5221],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4553,5213],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4558,5207],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4555,5198],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4546,5191],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4541,5190],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4527,5187],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4519,5194],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4515,5202],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4507,5226],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4526,5230],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4530,5236],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4519,5240],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4489,5253],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4484,5250],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4483,5258],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4496,5299],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4488,5313],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4489,5337],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4493,5348],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4414,5380],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4377,5389],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4368,5404],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4343,5402],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4336,5397],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4304,5404],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4311,5414],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4295,5367],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4302,5363],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4303,5336],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4308,5324],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4296,5321],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4291,5312],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4280,5302],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4284,5290],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4311,5309],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4312,5295],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4327,5293],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4336,5290],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4346,5277],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4356,5276],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4356,5289],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4356,5261],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4337,5262],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4337,5267],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4313,5259],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4308,5255],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4306,5243],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4297,5236],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4291,5251],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4284,5241],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4294,5231],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4277,5228],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4281,5216],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4315,5237],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4320,5252],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4322,5261],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4322,5229],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4321,5222],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4342,5222],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4334,5230],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4344,5260],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4355,5270],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3743, 3221],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3755, 3219],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3751, 3211],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3759, 3203],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3764, 3210],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3785, 3196],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3792, 3170],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3799, 3162],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3778, 3159],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3846, 3108],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3876, 3118],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3893, 3110],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3935, 3235],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3947, 3253],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3915, 3247],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3908, 3256],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3903, 3239],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3842, 3237],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3935, 3152],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3912, 3159],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3950, 3133],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3896, 3128],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3955, 3103],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3955, 3086],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3934, 3078],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3889, 3183],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3832, 3164],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3874, 3171],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3858, 3188],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3876, 3210],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3881, 3332],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3800, 3376],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [3754, 3320],
},
{
    "name": "Iron",
    "group": "iron",
    "icon": "iron",
    "coords": [4051, 3480],
},
// METEORITE
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3905, 4597],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3883, 4602],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3857, 4594],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3854, 4586],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3824, 4584],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3816, 4597],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3825, 4607],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3829, 4556],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3807, 4563],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3796, 4542],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3803, 4533],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3784, 4528],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3738, 4543],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3730, 4542],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3728, 4525],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3749, 4559],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3753, 4570],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3761, 4584],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3757, 4582],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3755, 4592],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3751, 4595],
},
{
    "name": "Meteorite",
    "group": "meteorite",
    "icon": "meteorite",
    "coords": [3752, 4604],
},
// STONE
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3716, 4568],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3704, 4566],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3707, 4560],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3693, 4554],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3689, 4552],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3689, 4543],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3663, 4552],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3650, 4557],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3640, 4562],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3627, 4558],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3622, 4554],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3606, 4548],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3621, 4518],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3613, 4512],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3624, 4526],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3656, 4519],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3342, 4636],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3347, 4627],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3352, 4621],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3356, 4616],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3360, 4610],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3365, 4617],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3358, 4626],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3365, 4610],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3367, 4625],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3354, 4633],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3364, 4633],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3371, 4630],
},
{
    "name": "Stone",
    "group": "stone",
    "icon": "stone",
    "coords": [3373, 4621],
},
// TOMATO
{
    "name": "Tomato",
    "group": "tomato",
    "icon": "tomato",
    "coords": [4414, 4900],
},
{
    "name": "Tomato",
    "group": "tomato",
    "icon": "tomato",
    "coords": [4418, 4891],
},
{
    "name": "Tomato",
    "group": "tomato",
    "icon": "tomato",
    "coords": [4371, 4857],
},
{
    "name": "Tomato",
    "group": "tomato",
    "icon": "tomato",
    "coords": [4374, 4841],
},
{
    "name": "Tomato",
    "group": "tomato",
    "icon": "tomato",
    "coords": [4359, 4849],
},
{
    "name": "Tomato",
    "group": "tomato",
    "icon": "tomato",
    "coords": [4349, 4804],
},
{
    "name": "Tomato",
    "group": "tomato",
    "icon": "tomato",
    "coords": [4336, 4775],
},
{
    "name": "Tomato",
    "group": "tomato",
    "icon": "tomato",
    "coords": [4187, 4676],
},
{
    "name": "Tomato",
    "group": "tomato",
    "icon": "tomato",
    "coords": [4137, 4629],
},
// CORN
{
    "name": "Corn",
    "group": "corn",
    "icon": "corn",
    "coords": [4736, 4662],
},
{
    "name": "Corn",
    "group": "corn",
    "icon": "corn",
    "coords": [4376, 4853],
},
{
    "name": "Corn",
    "group": "corn",
    "icon": "corn",
    "coords": [4380, 4859],
},
{
    "name": "Corn",
    "group": "corn",
    "icon": "corn",
    "coords": [4367, 4853],
},
{
    "name": "Corn",
    "group": "corn",
    "icon": "corn",
    "coords": [4331, 4769],
},
{
    "name": "Corn",
    "group": "corn",
    "icon": "corn",
    "coords": [4327, 4766],
},
{
    "name": "Corn",
    "group": "corn",
    "icon": "corn",
    "coords": [4304, 4771],
},
// COTTON
{
    "name": "Cotton",
    "group": "cotton",
    "icon": "cotton",
    "coords": [4358, 4782],
},
// CHILI
{
    "name": "Chili",
    "group": "chili",
    "icon": "chili",
    "coords": [4410, 4895],
},
{
    "name": "Chili",
    "group": "chili",
    "icon": "chili",
    "coords": [4240, 4697],
},
{
    "name": "Chili",
    "group": "chili",
    "icon": "chili",
    "coords": [4150, 4632],
},
{
    "name": "Chili",
    "group": "chili",
    "icon": "chili",
    "coords": [4145, 4626],
}
]
